name: GCP App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runCheckov:
        description: 'Run Checkov Scan'
        required: true
        type: boolean
        default: false

env:
  ENVIRONMENT: 'prod'
  WORKING_DIRECTORY: '.'
  TF_VERSION: '1.11.0'
  # GCP specific backend configurations
  GCS_BUCKET: 'bkt-terraform-backend'
  GCS_PREFIX: 'terraform/state'

jobs:
  deploy:
    # Pointing to the local reusable workflow (ensure this path is correct based on your repo structure)
    uses: ./.github/workflows/terraform-pipeline.yml
    with:
      workingDirectory: ${{ env.WORKING_DIRECTORY }}
      bucket: ${{ env.GCS_BUCKET }}
      prefix: ${{ env.GCS_PREFIX }}/${{ env.ENVIRONMENT }}
      environment: ${{ env.ENVIRONMENT }}
      terraformVersion: ${{ env.TF_VERSION }}
      runCheckov: ${{ github.event.inputs.runCheckov || false }}
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
